name: automatic-video-colorization
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.11.0=py36h06a4308_0
  - astor=0.8.1=py36_0
  - blas=1.0=mkl
  - c-ares=1.16.1=h7b6447c_0
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - cupti=10.0.130=0
  - cycler=0.10.0=py36_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.2.10=he6710b0_2
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.4=h5ab3b9f_0
  - gast=0.4.0=py_0
  - glib=2.66.1=h92f7085_0
  - grpcio=1.31.0=py36hf8bcb03_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - h5py=2.10.0=py36hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - imageio=2.9.0=py_0
  - importlib-metadata=2.0.0=py_1
  - intel-openmp=2020.2=254
  - jpeg=9b=h024ee3a_2
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.3.0=py36h2531618_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.13.0.1=hd408876_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.2=heb0550a_3
  - markdown=3.3.3=py36h06a4308_0
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2=py36h817c723_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.2.0=py36h23d657b_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - mock=4.0.2=py_0
  - ncurses=6.2=he6710b0_1
  - numpy=1.19.2=py36h54aff64_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - olefile=0.46=py_0
  - openssl=1.1.1h=h7b6447c_0
  - pcre=8.44=he6710b0_0
  - pillow=8.0.1=py36he98fc37_0
  - pip=20.2.4=py36h06a4308_0
  - protobuf=3.13.0.1=py36he6710b0_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - python=3.6.12=hcff3b4d_2
  - python-dateutil=2.8.1=py_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - scipy=1.5.2=py36h0b6359f_0
  - setuptools=50.3.1=py36h06a4308_1
  - sip=4.19.8=py36hf484d3e_0
  - six=1.15.0=py36h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tensorboard=1.13.1=py36hf484d3e_0
  - tensorflow=1.13.1=gpu_py36h3991807_0
  - tensorflow-base=1.13.1=gpu_py36h8d69cac_0
  - tensorflow-estimator=1.13.0=py_0
  - tensorflow-gpu=1.13.1=h0d30ee6_0
  - termcolor=1.1.0=py36_1
  - tk=8.6.10=hbc83047_0
  - tornado=6.0.4=py36h7b6447c_1
  - werkzeug=1.0.1=py_0
  - wheel=0.35.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - chardet==3.0.4
    - decorator==4.4.2
    - idna==2.10
    - imageio-ffmpeg==0.4.2
    - moviepy==1.0.3
    - opencv-contrib-python==4.4.0.46
    - proglog==0.1.9
    - pypng==0.0.20
    - requests==2.25.0
    - tqdm==4.53.0
    - urllib3==1.26.2
prefix: /home/chenyang/anaconda3/envs/fa-video-colorization

